### ISSUE TITLE
console error

### ISSUE THREAD

**Issue by zemBADEV** [TGIANN/tgiann-anti-duplicate-vehicle#2]
InvokeNative: execution failed: Tried to access invalid entity: 233821
SCRIPT ERROR: Execution of native 00000000e8522d58 in script host failed: Tried to access invalid entity: 233821
GetVehicleNumberPlateText (GetVehicleNumberPlateText.lua:3)
[   script:tgiann-anti-duplicate-vehicle] > handler (@tgiann-anti-duplicate-vehicle/server.lua:28)

This happens when i spawn any vehicle

**Comment by TGIANN** [comment]
fixed in new version
